### ISSUE TITLE
Mesos-related updates to the 3.x version

### ISSUE THREAD

**Issue by misterbisson** [misterbisson/triton-couchbase#4]
Couchbase support for these Mesos-related tasks:
- [x] [Pass Couchbase user/pass as an environment var](https://github.com/joyent/mesos-dockerfiles/issues/13)
- [x] [Pass service names as environment vars](https://github.com/joyent/mesos-dockerfiles/issues/12)
- [x] [Pass Consul location via environment var](https://github.com/joyent/mesos-dockerfiles/issues/10)

Do these in 3.x, then [integrate 4.x](https://github.com/misterbisson/triton-couchbase/issues/5) based on @tgross' work in https://github.com/misterbisson/triton-couchbase/pull/1

**Comment by misterbisson** [comment]
Fixes for this are in https://github.com/misterbisson/triton-couchbase/pull/6, with test case in https://github.com/misterbisson/clustered-couchbase-in-containers/pull/12

**Comment by misterbisson** [comment]
Releases:
- https://github.com/misterbisson/triton-couchbase/releases/tag/enterprise-3.0.3-r4
- https://github.com/misterbisson/clustered-couchbase-in-containers/releases/tag/1.2
